### ISSUE TITLE
Trezor Connect - Login signature verification process 

### ISSUE THREAD

**Issue by johndoeiam** [trezor/connect#232]
...

**Comment by prusnak** [comment]
Can you describe more what is the problem?

I don't understand the sentence "as far as i can tell from bitcore the signature is valid but not on the trezor function". 

Maybe just edit your post above and add into comments what is the real output of console.log and what is your expectation.

**Comment by florincm** [comment]
the result from 
```
const
	bitcore = require('bitcore-lib'),
	{PublicKey} = bitcore,
	{BufferWriter} = bitcore.encoding,
	{Signature, ECDSA, Hash} = bitcore.crypto,
	{sha256sha256, sha256} = Hash;

function verify(hiddenChallenge, visualChallenge, pubKey, signature, version) {
	hiddenChallenge = Buffer.from(hiddenChallenge, 'hex');
	visualChallenge = Buffer.from(visualChallenge);
	pubKey = new PublicKey(Buffer.from(pubKey, 'hex'));
	signature = Signature.fromCompact(Buffer.from(signature, 'hex'));

	let message;

	if (version === 1) {
		message = Buffer.concat([hiddenChallenge, visualChallenge]);
	} else if (version === 2) {
		message = Buffer.concat([sha256(hiddenChallenge), sha256(visualChallenge)]);
	} else {
		throw new Error('Unknown version');
	}

	const
		magicBytes = Buffer.from('Bitcoin Signed Message:\n'),
		prefix1 = BufferWriter.varintBufNum(magicBytes.length),
		prefix2 = BufferWriter.varintBufNum(message.length),
		buf = Buffer.concat([prefix1, magicBytes, prefix2, message]),
		hash = sha256sha256(buf);

	return ECDSA.verify(hash, signature, pubKey);
}

const
	hidden = "cd8552569d6e4509266ef137584d1e62c7579b5b8ed69bbafa4b864c6521e7c2", // Use random value
	visual = "2015-03-23 17:39:22",
	pubKey = "023a472219ad3327b07c18273717bb3a40b39b743756bf287fbd5fa9d263237f45",
	signature = "20f2d1a42d08c3a362be49275c3ffeeaa415fc040971985548b9f910812237bb41770bf2c8d488428799fbb7e52c11f1a3404011375e4080e077e0e42ab7a5ba02";

console.log(verify(hidden, visual, pubKey, signature, 2));
```
is 
```
true
```

but the result from
```
const
	bitcore = require('bitcore-lib'),
	{PublicKey} = bitcore,
	{BufferWriter} = bitcore.encoding,
	{Signature, ECDSA, Hash} = bitcore.crypto,
	{sha256sha256, sha256} = Hash;

function verify(hiddenChallenge, visualChallenge, pubKey, signature, version) {
	hiddenChallenge = Buffer.from(hiddenChallenge, 'hex');
	visualChallenge = Buffer.from(visualChallenge);
	pubKey = new PublicKey(Buffer.from(pubKey, 'hex'));
	signature = Signature.fromCompact(Buffer.from(signature, 'hex'));

	let message;

	if (version === 1) {
		message = Buffer.concat([hiddenChallenge, visualChallenge]);
	} else if (version === 2) {
		message = Buffer.concat([sha256(hiddenChallenge), sha256(visualChallenge)]);
	} else {
		throw new Error('Unknown version');
	}

	const
		magicBytes = Buffer.from('Bitcoin Signed Message:\n'),
		prefix1 = BufferWriter.varintBufNum(magicBytes.length),
		prefix2 = BufferWriter.varintBufNum(message.length),
		buf = Buffer.concat([prefix1, magicBytes, prefix2, message]),
		hash = sha256sha256(buf);

	return ECDSA.verify(hash, signature, pubKey);
}

const
	hidden = "cd8552569d6e4509266ef137584d1e62c7579b5b8ed69bbafa4b864c6521e7c2", // Use random value
	visual = "2015-03-23 17:39:22",
	pubKey = "0384062c05d986f50e970dcce8b8e854187e785a51a7928ae2ed7287d27dd3d966",
	signature = "3044022027a7864582b63a66c089d132e8ede016ef25035651d921f91bd6104e66ccb92e02205c4b12f6ffe5c3819897ddfe2c4fa1f0352fc4d5233a2c00c2c4232cc13461a2";

console.log(verify(hidden, visual, pubKey, signature, 2));
```
is
```

/Users/admin/Desktop/auth.co/node_modules/bitcore-lib/lib/util/preconditions.js:14
      throw new errors.InvalidArgument(argumentName, message, docsPath);
      ^
Invalid Argument: Error: i must be 0, 1, 2, or 3
Error
    at new NodeError (/Users/admin/Desktop/auth.co/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Object.checkArgument (/Users/admin/Desktop/auth.co/node_modules/bitcore-lib/lib/util/preconditions.js:14:13)
    at Function.Signature.fromCompact (/Users/admin/Desktop/auth.co/node_modules/bitcore-lib/lib/crypto/signature.js:51:5)
    at verify (/Users/admin/Desktop/auth.co/check.js:12:24)
    at Object.<anonymous> (/Users/admin/Desktop/auth.co/check.js:40:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by prusnak** [comment]
Where does (valid)

```
	pubKey = "023a472219ad3327b07c18273717bb3a40b39b743756bf287fbd5fa9d263237f45",
	signature = "20f2d1a42d08c3a362be49275c3ffeeaa415fc040971985548b9f910812237bb41770bf2c8d488428799fbb7e52c11f1a3404011375e4080e077e0e42ab7a5ba02";
```

and (broken)

```
	pubKey = "0384062c05d986f50e970dcce8b8e854187e785a51a7928ae2ed7287d27dd3d966",
	signature = "3044022027a7864582b63a66c089d132e8ede016ef25035651d921f91bd6104e66ccb92e02205c4b12f6ffe5c3819897ddfe2c4fa1f0352fc4d5233a2c00c2c4232cc13461a2";
```

Come from?

**Comment by johndoeiam** [comment]
if you run the script from the main issue information you will get the object with that information

**Comment by prusnak** [comment]
I am not going to run any scripts. If you want help, please provide the info.

**Comment by johndoeiam** [comment]
to understand what the script does using the official bitcore modules... is trying to replicate the same behaviour that trezor does on login but via javascript reather then the hadrware device

and i am trying to understand how does the trezor encode the signature to make it valid for the official server function that validates it.

**Comment by prusnak** [comment]
@johndoeiam have you found the bug? what was the issue?

**Comment by johndoeiam** [comment]
missing i 

```
  ecdsa.signRandomK();
  ecdsa.calci();
```
and needed to convert it to a compact signature.

```
.toCompact()
```

**Comment by prusnak** [comment]
Thanks!
