### ISSUE TITLE
How can I run trezor-connect script in node command?

### ISSUE THREAD

**Issue by bytefly** [trezor/connect#248]
I downloaded the trezor-connect module with "npm install trezor-connect" command and wrote a demo script to run, just call TrezorConnect.getPublicKey, but it has error：
`/data/disk1/workdir/trezor-test/node_modules/trezor-connect/lib/data/ConnectSettings.js:39
    supportedBrowser: !/Trident|MSIE/.test(navigator.userAgent),
                                           ^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/data/disk1/workdir/trezor-test/node_modules/trezor-connect/lib/data/ConnectSettings.js:39:44)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/data/disk1/workdir/trezor-test/node_modules/trezor-connect/lib/index.js:72:24)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
`
Does it only run in browser?

**Comment by szymonlesisz** [comment]
only browsers are supported for now, but we are working on that

**Comment by jjgonecrypto** [comment]
Any update on this @szymonlesisz ?

**Comment by bitcodernull** [comment]
Any update now?
